src/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    
    path('', include('mylist.urls')),
    path("song-list/", include('song.urls')),
    path("user/", include('user.urls')),
    path("recommend/",include('recommend.urls')),
    path("elastic/", include('elastic.urls')),
]

src/song/urls.py
from django.urls import path
from .views import song_list,search_view, add_to_search,add_to_tjlist,ky_song_list,add_to_kylist, SearchView

 
app_name = 'song'

urlpatterns = [
    path('', song_list, name='song-list'),
    path('ky/',ky_song_list, name='ky_song_list'),
    path('search/', SearchView.as_view(), name='song-search'),
    path('add-to-database/', add_to_search, name='add_to_database'),
    path('add-to-tjlist/', add_to_tjlist, name='add-to-tjlist'),
    path('add-to-kylist/', add_to_kylist, name='add-to-kylist'),
]

src/user/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView
from mylist.views import mylist
from . import views


app_name = 'user'

urlpatterns = [
    path('',views.base, name='base'),
    path('main/',views.main, name='home'), # 메인페이지(top10, user님 취향에 맞는 콘텐츠)로 랜딩
    path('sign-up/', views.sign_up_view, name='sign-up'), # 회원가입 페이지로 랜딩
    path('sign-in/', views.sign_in_view, name='sign-in'), # 로그인 페이지로 랜딩
    path('sign-in/', LoginView.as_view(template_name='user/sign-in.html'), name='sign-in'),
    path('kakao/', views.to_kakao, name='kakao'), # 카카오 로그인 하기
    path('kakao/callback/', views.from_kakao, name='kakako_login'), # 카카오 로그인에서 정보 가져오기
    path('logout/', views.log_out, name='logout'), # 로그아웃
    path('mypage/',views.my_page, name='mypage'), # 마이페이지
    path('pwchange/',views.pw_change, name='pwchange'), # 비밀번호 변경
    path('email_ajax/',views.email_ajax, name='email_ajax'), # 인증 메일 보내기
    path('certify_ajax/',views.certify_ajax, name='certify_ajax'), # 인증번호 확인
    path('isid/',views.is_id, name='is_id'), # 임시 비밀번호 발급(아이디는 알고 비번은 모를 때)
    path('my-modify/',views.my_modify, name='my_modify'), # 프로필 이미지 수정
]

src/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Permission
from django.contrib.auth.models import BaseUserManager

class CustomUserManager(BaseUserManager):
    def create_user(self, user_id, password=None, **extra_fields):
        if not user_id:
            raise ValueError('user_id 필드가 비어 있습니다.')
        user = self.model(user_id=user_id, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, user_id, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(user_id, password, **extra_fields)

class User(AbstractUser):
    
    class Meta:
        db_table = 'user'

    objects = CustomUserManager()
        
    id = models.AutoField(primary_key = True) # 일련번호 id
    
    GENDER_MAIL = 'Male'
    GENDER_FEMAIL = 'Female'
    GENDER_CHOICES = ((GENDER_MAIL, 'Male'),(GENDER_FEMAIL, 'Female')) # 성별 선택 항목 생성
    
    LOGIN_EMAIL = 'email'
    LOGIN_KAKAO = 'kakao'
    LOGIN_CHOICES = ((LOGIN_EMAIL,'Email'),(LOGIN_KAKAO, 'Kakao')) # 로그인 방식 항목 생성
    
    user_id = models.CharField(max_length=40,blank=True, unique=True) # 로그인용 id
    USERNAME_FIELD = 'user_id' # django의 기본 User 모델에서 username으로 user_id 사용하겠다고 명시 커스텀
    
    #name = models.CharField(max_length=30,blank=True)
    name = models.CharField(max_length=30,blank=True)
    nickname = models.CharField(max_length=30,blank=True) # 닉네임
    birthday = models.DateField(blank=True, null=True) # 생년월일
    gender = models.CharField(choices=GENDER_CHOICES, max_length=10, default=GENDER_MAIL) # 성별
    profile_img = models.ImageField(upload_to='profile_img/', default='/static/img/user_default.png') # 프로필 사진
    login_method = models.CharField(choices=LOGIN_CHOICES, max_length=20, default=LOGIN_EMAIL) # 로그인 정보(이메일/카카오)

    

src/user/views.py
import json
with open('secrets.json') as f:
    secrets = json.loads(f.read())
import random
import string
import datetime
from random import randint
from django.http import JsonResponse
import requests
from django.shortcuts import render, redirect, reverse
from . import models
from .models import User
from django.contrib import auth, messages
from django.contrib.auth import get_user_model, authenticate, login
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
import uuid
from .utils import parse_birthday
from django.conf import settings
from django.http import HttpResponseRedirect


# 가입 유도하는 페이지(landing.html)로의 랜딩부
def base(request):
    user = request.user.is_authenticated # 가입한 사람인지 확인
    # True, False반환
    if not user: # 가입 안 한 사람이라면
        return render(request, 'landing.html') # 가입 유도 랜딩 페이지로
    return redirect('/') # 가입 한 사람이면 그냥 일반 메인 페이지로


#@login_required # 로그인 된 사람
def main(request): 
    print('로그인 된 사람') 
    return render(request, 'main.html') # 일반 메인 페이지로 랜딩


certify = False # 메일 인증 상태 False로 초기화

# 회원가입
def sign_up_view(request):
    print('회원가입 시도') #인증번호
    global certify # 메일 인증 상태에 대한 변수 'certify'를 전역변수로 선언
    if request.method == 'GET':  # 요청이 get으로 들어온다면
        is_user = request.user.is_authenticated # 가입된 유저인지 여부 request 요청, 결과를 is_user 변수에 저장
        if is_user: # 가입 여부 True라면
            return redirect('/') # 메인 페이지로 리다이렉트

        return render(request, 'user/signup.html') # get에 대한 리턴으로 signup.html로 랜딩함

    elif request.method == 'POST':  # 요청이 post로 들어온다면
        global certify_num
        data = json.loads(request.body.decode('utf-8')) # POST 요청에서 전달받은 본문(body) 가져와 "data"라는 변수에 저장, JSON 형식의 문자열을 딕셔너리로 변환
        name = data['username'] 
        user_id = data['user_id'] 
        password1 = data['password1']
        password2 = data['password2']
        nickname = data['nickname']
        email = data['email']
        birthday = data['birthday']
        gender = data['gender']
 
        err_msg = '' # 에러 메시지 초기화

        # user_id = str(uuid.uuid4())

        if name == '': # 이름 공백일 때
            err_msg = '이름을 적어주세요.'
        if user_id == '' or password1 == '': # 아이디/비번 공백으로 로그인 시도 때
            err_msg = '아이디 및 패스워드를 확인해주세요'
        if nickname == '': # 닉네임 공백일 때
            err_msg = '닉네임을 적어주세요.'
        if email == '': # 이메일 공백일 때
            err_msg = '이메일을 적어주세요.'
        if birthday == '': # 생일 공백일 때
            err_msg = '생년월일을 적어주세요.'
        if gender == '1': # 성별 디폴트값일 때
            err_msg = '성별을 적어주세요.'
        if password1 != password2: # 비번과 비번 확인이 다를 때
            err_msg = '비밀번호가 일치하지 않습니다.'
        # if not certify: # 이메일 인증 하지 않았을 때
        #     err_msg = '이메일을 인증해주세요.'
            
        is_it = get_user_model().objects.filter(user_id=user_id) # 지금 POST 요청에서 받은 user_id과 기존 DB의 user_id이 일치할 경우
        is_it2 = get_user_model().objects.filter(email=email) # 지금 POST 요청에서 받은 email과 기존 DB의 email이 일치할 경우
        
        if is_it:
            err_msg = '사용자가 존재합니다.'
        if is_it2:
            err_msg = '이메일이 중복됩니다.'
        
     
        
        if len(err_msg) > 1: # 만약 err_msg가 빈 문자열이 아니라면, 오류 발생한 것으로 간주
            return JsonResponse({'status':'error','error':err_msg}) # 'error' 키와 함께 err_msg가 포함된 딕셔너리를 json 형식으로 응답으로 보내줌

        # get_user_model() 함수: Django에서 제공하는 내장 함수로서, 장고의 auth 앱에서 사용자 모델을 가져오는 역할
        User.objects.create_user(username=user_id, user_id=user_id, password=password1, nickname=nickname, email=email, birthday=birthday, gender=gender, name=name)
       
        return JsonResponse({'status':'success'})


# 로그인
def sign_in_view(request): 
    if request.method == 'POST':
        user_id = request.POST.get('user_id') 
        password = request.POST.get('password')
        me = auth.authenticate(request, user_id=user_id, password=password) # 장고의 auth 앱 사용, 사용자 ID/PW 확인
        print("로그인 시도")
        if not me:  # ID/PW 맞지 않는다면
            return render(request, 'user/signin.html', {'error': '아이디 혹은 비밀번호가 틀렸습니다.'}) # 에러 발생 후 로그인 창으로 랜딩
        auth.login(request, me) # ID/PW 잘 맞는다면, me 정보로 로그인
        return redirect('/') # 로그인 된 채로 main 페이지로 랜딩
    else: 
        is_user = request.user.is_authenticated 
        if is_user:
            return redirect('/')
        return render(request, 'user/signin.html')
    

# 로그아웃
@login_required
def log_out(request):
    auth.logout(request) # 장고의 auth 앱 사용, 로그아웃
    messages.success(request, '로그아웃이 완료되었습니다👌🏻')
    return redirect('/')


# (admin용) 회원 관리 페이지
@login_required
def user_view(request):
    if request.method == 'GET':
        user_list = User.objects.all().exclude(user_id=request.user.user_id)
        return render(request, 'user/user_list.html', {'user_list': user_list})



# 카카오 로그인 시도
def to_kakao(request):
    REST_API_KEY = secrets['REST_API_KEY']
    REDIRECT_URI = 'http://alsong-dlsong.com/user/kakao/callback'
    
    return redirect(
        f'https://kauth.kakao.com/oauth/authorize?client_id={REST_API_KEY}&redirect_uri={REDIRECT_URI}&response_type=code')


# 카카오 로그인에서 필요 정보 가져오기
def from_kakao(request):
    print("카카오API 접속 시도")
    REST_API_KEY = secrets['REST_API_KEY']
    REDIRECT_URI = 'http://alsong-dlsong.com/user/kakao/callback'
    code = request.GET.get('code', 'None')
    if code is None:
        # 코드 발급 x일 경우
        return redirect('/')
    headers = {'Content-type': 'application/x-www-form-urlencoded;charset=utf-8'}
    data = {
        'client_id': REST_API_KEY,
        'redirect_uri': REDIRECT_URI,
        'code': code,
        'grant_type': 'authorization_code',
    }
    response = requests.post('https://kauth.kakao.com/oauth/token', headers=headers, data=data)
    res_dict = response.json() 
    if 'error' in res_dict or 'access_token' not in res_dict:
        # 에러 발생 처리
        return redirect('/')
    access_token = res_dict.get('access_token', None)
    headers = {
        'Content-type': 'application/x-www-form-urlencoded;charset=utf-8',
        'Authorization': 'Bearer {}'.format(access_token)
    }
    response = requests.get('https://kapi.kakao.com/v2/user/me', headers=headers)
    res_dict = response.json()
    
    kakao_account = res_dict.get('kakao_account')
    user_id = res_dict.get('id')
    properties = res_dict.get('properties')

    username = res_dict.get('id')
    email = res_dict.get('kakao_account', {}).get('email', None)
    uid = 'kakao_{}'.format(res_dict.get('id'))
    
    nickname = res_dict.get('kakao_account', {}).get('profile', {}).get('nickname', 'Unknown')
    profile_img = properties.get('profile_image', None)
    gender = kakao_account.get('gender', None)
    birthday = kakao_account.get('birthday', None)
    modified_birthday = parse_birthday(birthday)
    print("카카오API에서 data 가져오기 성공!")
    
    try:
        user = get_user_model().objects.get(email=email)

        if user.login_method != models.User.LOGIN_KAKAO:
            print('카카오로 가입하지 않은 다른 아이디가 존재함')
            return redirect('/')


    except:
        print("카카오API로 받은 data 저장 시도")
        user = models.User.objects.create(user_id=user_id, username=username, nickname=nickname, profile_img=profile_img, 
                                   email=email, login_method=models.User.LOGIN_KAKAO, birthday=modified_birthday, gender=gender)

        user.set_unusable_password()
        user.save()
    
    print("카카오API로 로그인 시도")
    auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
    return redirect('/')


@login_required
def my_page(request):
    print("마이페이지 접속 시도")
    print(request.method)
    if request.method == 'POST':
        pass
    else:
        user = request.user
        users = User.objects.filter(user_id=user)

        print(user)
        print(user.username)
        err = False
        if user.login_method != 'email' and (user.birthday is None or user.gender is None):
            err = '카카오톡으로 로그인 하신 경우에는 반드시 생일, 성별을 설정해주세요!'

        data = {'user':users}
        return render(request, 'user/mypage.html', data)
    

# 비밀번호 변경
@login_required
def pw_change(request):
    if request.method == 'POST':
        pw1 = request.POST.get('password1', None)
        pw2 = request.POST.get('password2', None)
        if pw1 != pw2:
            return render(request, 'user/pwchange.html', {'error': '비밀번호가 일치하지 않습니다.'})
        user = request.user
        user.set_password(pw2)
        user.save()
        auth.logout(request)
        return redirect('/')

    else:
        if request.user.login_method != 'email':
            return redirect('/user/mypage')
        return render(request, 'user/pwchange.html')


certify_num = ''

# 이메일 인증번호 보내기
def email_ajax(request):
    global certify_num
    if request.method == 'POST':
        print('hi')
        certify_num = randint(10000, 99999)

        email = json.loads(request.body)
        print(email)
        send_mail('알song달song 회원가입 인증 메일입니다.',
                  f'아래의 인증번호를 입력해주세요🔐✨\n\n인증번호 : {certify_num}', 'jibeenpark@gmail.com', [email],
                  fail_silently=False)
        context = {
            'result': '인증번호 발송이 완료되었습니다.',
        }

    return JsonResponse(context)

# 인증번호 확인
def certify_ajax(request):
    global certify
    if request.method == 'POST':
        num = json.loads(request.body)
        result_msg = ''
        if num == str(certify_num):
            result_msg = '인증번호가 일치합니다.'
            certify = True
        else:
            result_msg = '인증번호가 다릅니다.'

        context = {
            'result': result_msg,
        }
    return JsonResponse(context)


# 임시 비밀번호 발급(아이디는 알고 비밀번호 모를 때)
def is_id(request):
    data = json.loads(request.body)
    try:
        # 아이디 유무 확인
        user = get_user_model().objects.get(username=data)
        # 카카오로 회원가입 한 경우 안 됨
        if user.login_method != 'email':
            context = {'result': '카카오로 로그인해주세요.', 'sns': 'sns'}
            return JsonResponse(context)
        email = user.email
        # 임시 비밀번호 생성
        temp_pw = ''
        for _ in range(15):

src/templates/user/home.html
{% extends 'navbar.html' %}
{% block content%}
    <p>로그인 성공</p>
    <a href="/mypage">마이페이지😀</a>
    <a href="{% url 'user:logout' %}">로그 아웃🚗</a>
   
{% endblock %}
{% block script %}
<script>
    function sendMail(){
        data = $('#text').val();
        $.ajax({
            type:'POST',
            url:'/email_ajax/',
            data:JSON.stringify(data),
            success:function(json){
                alert(json.result);
            }

       });
    submitBtn.removeEventListener('click',sendMail)
    submitBtn.addEventListener('click',certifyMail)
    submitBtn.innerText = '인증번호 확인'
    }
    function certifyMail(){
        data = $('#text2').val();
        $.ajax({
            type:'POST',
            url:'/certify_ajax/',
            data:JSON.stringify(data),
            success:function(json){
                alert(json.result);
            }
        })
        submitBtn.removeEventListener('click',certifyMail)
        submitBtn.addEventListener('click',sendMail)
        submitBtn.innerText = '인증번호 보내기'
    };
    
    const submitBtn = document.getElementById('submit')
    submitBtn.addEventListener('click',sendMail)
    
    $.ajaxSetup({
        headers: { "X-CSRFToken": '{{csrf_token}}' }
      });
</script>
{% endblock%}

src/templates/user/pwchange.html
{% extends 'navbar.html' %}

{% block title %} | 비밀번호 변경{% endblock %}

{% block content%}
    <div>비밀번호 변경</div>
    <form action="/pwchange/" method="post">
        {% csrf_token %}
        <label for="password1">변경할 비밀번호</label>
        <input type="password" name="password1">
        <label for="password1">비밀번호 확인</label>
        <input type="password" name="password2">
        <div class="err_box">
            {%if error %}
            {{error}}
            {%endif %}
        </div>
        <button type="submit">변경😁</button>
    </form>
{% endblock %}

src/templates/user/signin.html
{% extends 'navbar.html' %}

{% block title %} | 로그인{% endblock%}

{% block style %}
<link rel="stylesheet" href="/static/css/signin-html.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
              integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
              crossorigin="anonymous" referrerpolicy="no-referrer"/>
        {#            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">#}
<style></style>
{% endblock %}
{% block content %}

<div class="main-html">
    <div class="login-box">
        <div class="login-box-style"></div>
        <a class="login-box-text-1" href="/">
            <img style="width: 100%; height: 100%;" src="/static/img/알송달송-로고-final_여백제거.png">
        </a>
        <form style="width: 70%;" method="post" action="/user/sign-in/">
            {% csrf_token %}
            <div class="basic-input">
                <div class="input-box">
                    <input class="input-box-text" type="text" id="user_id" name="user_id" placeholder="아이디">
                </div>
                <div class="input-box">
                    <input class="input-box-text" type="password" id="password" name="password" placeholder="비밀번호">
                </div>
            </div>
            <hr>
            <div class="login-button">
                <button class="btn login-button-style" type="submit">로그인</button>
            </div>
            <div id="social-login">
                <button style="width: 72%;" class="button is-small" id="kakao-btn" type="button">
                            <span style="font-size: 13px;" class="icon">
                              <i class="fas fa-comment"></i>
                              카톡 로그인
                            </span>
                    <!-- <span>카카오톡으로 로그인하기</span> -->
                </button>
            </div>
        </form>
        <div class="id-password-box">
            <div class="id-text">아이디 찾기</div>
            <div class="password-text">비밀번호 찾기</div>
        </div>
        <div class="sign-up-box">
		<div class="sign-up-box-text-1"> 아직 계정이 없으신가요?<br>
            </div>
	    <a class="sign-up-box-text-2" href="/user/sign-up/">가입후 코노 생활 업글하기!🎤✨</a>
        </div>
    </div>
</div>
{% if error %}
  <span id="error-message" style="display:none;">{{ error }}</span>
{% endif %}

{% endblock %}


{% block script %}
    <script>

        document.addEventListener('DOMContentLoaded', function() {
        const kakaoBtn = document.getElementById('kakao-btn')
        const errorMessageElement = document.getElementById('error-message');

        if (errorMessageElement) {
            // 본문에서 에러 메시지가 있다면 경고 창 띄우기
            alert(errorMessageElement.innerText);
        }

        kakaoBtn.addEventListener('click', () => {
            const url = '/user/kakao'
            window.location.href = url;
        })
        const findBtn = document.getElementById('find')
        const hiddenBox = document.getElementById('hidden_box')
        const findPw = document.getElementById('find_pw')
        findPw.addEventListener('click', () => {
            hiddenBox.hidden = false
        })
        const next1 = () => {

            data = document.getElementById('find_id').value
            $.ajax({
                type: 'POST',
                url: '/user/isid/',
                data: JSON.stringify(data),
                success: function (data) {
                    if (data.result) {
                        alert(data.result);
                    }
                    if ('ok' in data) {
                        window.location.reload()
                    } else if ('sns' in data) {
                        window.location.reload()
                    }

                }

            });
        }});
        
    </script>
{% endblock %}

src/templates/user/signup.html
{% extends 'navbar.html' %}
{% block style %}
<link rel="stylesheet" href="/static/css/signup-html.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
              integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
              crossorigin="anonymous" referrerpolicy="no-referrer"/>
        {#            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">#}
<style></style>
{% endblock %}
{% block title %} | 회원가입{% endblock %}




{% block content %}

<div class="main-html">
    <div class="sign-up-box">
        <div class="sign-up-box-style"></div>
        <div class="sign-up-box-text-1">회원가입</div>
        <div class="basic-input">
            <div class="input-box">
                <input type="text" class="input-box-text" id="username" name="username" value="{{form.username}}" placeholder="이름">
            </div>

            <div class="input-box">
              <input type="text" class="input-box-text" id="user_id" name="user_id" value="{{form.user_id}}" placeholder="아이디">
            </div>

            <div class="input-box">
              <input type="password" class="input-box-text"  id="password1" name="password1" value="{{form.password1}}"  placeholder="비밀번호">
            </div>
            <div class="input-box">
              <input type="password" class="input-box-text"  id="password2" name="password2" value="{{form.password2}}"  placeholder="비밀번호 확인">
            </div>
            <div class="input-box">
              <input type="text" class="input-box-text"  type="text" name="nickname" maxlength="30" id="nickname" value="{{form.nickname}}"  placeholder="닉네임">
            </div>
            <div class="input-box">
                <input type="email" class="input-box-text" name="email" id="email" value="{{form.email}}" placeholder="이메일">
            </div>
            <div  class="input-box">
                <input type="date" class="input-box-text" name="birthday" id="birthday" value="{{form.birthday}}" placeholder="인증 번호">
            </div>

            <div class="input-box" style="width: 40%;">
                <select class="input-box-text" style="height: 30px; width: 80%;" aria-label="Default select example" name="gender" id="gender">
                    <option value="1" selected="">성별</option>
                    <option value="male">남성</option>
                    <option value="female">여성</option>
                </select>
            </div>
            <div class="sign-up-button">
                <button id='signBtn' class="btn sign-up-button-style" >회원가입</button>
            </div>
            <div class="sign-up-box-1">
                <a class="sign-up-box-text-2" href="{% url 'user:sign-in' %}">로그인 페이지로</a>
            </div>
        </div>
    </div>
</div>

    
{% endblock %}

{% block script %}
<script>
    $(document).ready(function () {
        const signBtn = document.getElementById('signBtn');
        $('#signBtn').on('click',()=>{
            console.log('클릭');
            const username = $('#username').val();
            const user_id = $('#user_id').val();
            const password1 = $('#password1').val();
            const password2 = $('#password2').val();
            const nickname = $('#nickname').val();
            const email = $('#email').val();
            const birthday = $('#birthday').val();
            const gender = $('#gender').val();
        
            
            $.ajax({
                type:'POST',
                url:'/user/sign-up/',
                data: JSON.stringify({
                    username:username,
                    user_id:user_id,
                    password1:password1,
                    password2:password2,
                    nickname:nickname,
                    email:email,
                    birthday:birthday,
                    gender:gender,
                }), // JSON.stringify(data),
                success:function(response){
                    const jsonResponse = response;
                    if (jsonResponse.status === 'success') {
                        var successMessage = "회원가입에 성공했습니다.";
                        alert(successMessage);
                        location.replace('{% url "user:sign-in" %}');
                    } else if (jsonResponse.status === 'error'){
                        var errorMessage = jsonResponse.error;
                        console.log(errorMessage)
                        alert(errorMessage)
                    }
                },
                error:function(request, status, error){
                    // 요청이 실패했을 때 실행할 코드
                    const data = JSON.parse(request.responseText);
                    console.log(data.message);
                    var errorMessage = "회원가입에 실패했습니다.";
                    alert(errorMessage);
                }
                })
        }) 
    });
    
    $.ajaxSetup({
        headers: { "X-CSRFToken": '{{ csrf_token }}' }
    });
</script>
{% endblock %}